times = ("Flamengo", "Palmeiras", "São Paulo", "Corinthians", "Internacional", "Atlético Mineiro", "Grêmio", "Santos", "Fluminense", "Cruzeiro", "Vasco da Gama", "Atlético Paranaense", "Chapecoense", "Botafogo", "Bahia", "Fortaleza", "Ceará", "Red Bull Bragantino", "Goiás", "Sport Recife")
print('Tabela')
print(times)
print('-='*30)
print(f'Os 5 primeiros colocados da tabela são :{times[0:5]}')
print('-='*30)
print(f'Os 4 ultimos colocados da tabela são : {times[-4:]}')
print('-='*30)
print(f'Os times em ordem alfabetica : {sorted(times)}')
print('-='*30)
poschapeco = times.index('Chapecoense') + 1
print(f'O time da chapecoense esta na posição {poschapeco}')
print('-='*30)
print(f'E os times q estao atras dele são {times[poschapeco:]}')
print('-='*30)